Altered the self issue
TristanSJones/armadillo pull request #2
Opened 2022-09-07 10:39 UTC by TristanSJones

Fixes #1 

Changes made in this Pull Request:
 - Changed the word self to ring_atoms in which ring_atoms is one atom group with all the atoms that have the potential to be atoms within rings in the given universe/all the atoms that will be rings that we want to stack

2022-09-12 14:50 UTC, TristanSJones commented
Fixes self issue described in #1. In addition, it adds tests for ring_distance, ring_normal, find_pi_stacking and find_pi_stacking_rings functions. As well as updated armadillo.py to resolve bugs that were discovered in the test process.

2022-09-13 15:13 UTC, micaela-matta requested changes
hi @TristanSJones, have a look at the comments and let me know if anything isn't clear! Great job towards your first PR 🥇

2022-09-13 15:13 UTC, micaela-matta commented on armadillo/tests/test_find_pi_stacking_rings.py
> +u = mda.Universe('g3.pdb', guess_bonds=True)
lines 12-17 should all be inside the `test_find_pi_stacking_rings` function

2022-09-13 15:13 UTC, micaela-matta commented on armadillo/tests/test_find_all_rings.py
> +u = mda.Universe('g3.pdb', guess_bonds=True)
line 12 should be inside the `test_find_all_rings` function; the docstring should be immediately after the `def` line.

2022-09-13 15:13 UTC, micaela-matta commented on armadillo/tests/test_normal_vector.py
> +u = mda.Universe('g3.pdb', guess_bonds=True)
same as for the other tests, every line/variable definition needed to run the test should be inside the test function

2022-09-13 15:13 UTC, micaela-matta commented on armadillo/tests/test_pi_stacking-individual.py
> +def test_armadillo_imported():
consider whether incorporating all tests into a single  `tests.py` file would make life easier :)

2022-09-13 15:13 UTC, micaela-matta commented on armadillo/tests/test_pi_stacking-individual.py
> +ring_list = armadillo.find_all_rings(u)
if you had a single `test.py` file, you could perhaps load the test `Universe` once, then pass it to all test functions.

2022-09-13 15:13 UTC, micaela-matta commented on armadillo/armadillo.py
> +        Universie is a MDAnalysis kit that
seen a few typos here and there:)

2022-09-13 15:13 UTC, micaela-matta commented on armadillo/armadillo.py
> +        Universie is a MDAnalysis kit that
would suggest replacing with something like: `MDAnalysis Universe containing topology and trajectory info`

2022-09-13 15:13 UTC, micaela-matta commented on armadillo/armadillo.py
> +        ring_cogs.append(ring.center_of_geometry())
why don't you use`ring_center`?
you could try list comprehension instead of a loop:)

2022-09-15 10:11 UTC, merged